// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfb7h7qCXy30HQVNtRSCknJWV6Pat-N-0',
    appId: '1:632689314541:web:726f1f28726ed5332d5ae4',
    messagingSenderId: '632689314541',
    projectId: 'mycart-e94b0',
    authDomain: 'mycart-e94b0.firebaseapp.com',
    storageBucket: 'mycart-e94b0.appspot.com',
    measurementId: 'G-4QYZJ76S67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClmTB-3KkKy6A1hgMw_eQEtrDZUrOSR-M',
    appId: '1:632689314541:android:d9f991f0b0fe75372d5ae4',
    messagingSenderId: '632689314541',
    projectId: 'mycart-e94b0',
    storageBucket: 'mycart-e94b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASeEXTrbVRHy3OFBaBfWtcKas-a6fxac8',
    appId: '1:632689314541:ios:71c2d21d37fc14c72d5ae4',
    messagingSenderId: '632689314541',
    projectId: 'mycart-e94b0',
    storageBucket: 'mycart-e94b0.appspot.com',
    iosBundleId: 'com.example.mycart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASeEXTrbVRHy3OFBaBfWtcKas-a6fxac8',
    appId: '1:632689314541:ios:71c2d21d37fc14c72d5ae4',
    messagingSenderId: '632689314541',
    projectId: 'mycart-e94b0',
    storageBucket: 'mycart-e94b0.appspot.com',
    iosBundleId: 'com.example.mycart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfb7h7qCXy30HQVNtRSCknJWV6Pat-N-0',
    appId: '1:632689314541:web:66a35286ab2a8b6f2d5ae4',
    messagingSenderId: '632689314541',
    projectId: 'mycart-e94b0',
    authDomain: 'mycart-e94b0.firebaseapp.com',
    storageBucket: 'mycart-e94b0.appspot.com',
    measurementId: 'G-614Z1GM3N0',
  );
}
